blank_issues_enabled: false
contact_links:
  - name: ğŸ˜ Contribution Guide
    url: https://github.com/dream-sports-labs/react-native-performance-tracker/blob/main/CONTRIBUTING.md
    about: Please read through before making any contribution.